/*

  Copyright (C) 2016 Michael Bur

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

#ifndef APP_HPP
#define APP_HPP

namespace App {
	static struct {
		std::string SMsCd;
	} Options;
}

char const* CivPicFilesNames[] = {
		"ADSCREEN.PIC",
		"ARCH.PIC",
		//"ASOUND.CVL",
		//"BACK0A.PAL",
		"BACK0A.PIC",
		//"BACK0M.PAL",
		"BACK0M.PIC",
		//"BACK1A.PAL",
		"BACK1A.PIC",
		//"BACK1M.PAL",
		"BACK1M.PIC",
		//"BACK2A.PAL",
		"BACK2A.PIC",
		//"BACK2M.PAL",
		"BACK2M.PIC",
		//"BACK3A.PAL",
		"BACK3A.PIC",
		//"BIRTH0.PAL",
		"BIRTH0.PIC",
		//"BIRTH1.PAL",
		"BIRTH1.PIC",
		//"BIRTH2.PAL",
		"BIRTH2.PIC",
		//"BIRTH3.PAL",
		"BIRTH3.PIC",
		//"BIRTH4.PAL",
		"BIRTH4.PIC",
		//"BIRTH5.PAL",
		"BIRTH5.PIC",
		//"BIRTH6.PAL",
		"BIRTH6.PIC",
		//"BIRTH7.PAL",
		"BIRTH7.PIC",
		//"BIRTH8.PAL",
		"BIRTH8.PIC",
		//"BLURB0.TXT",
		//"BLURB1.TXT",
		//"BLURB2.TXT",
		//"BLURB3.TXT",
		//"BLURB4.TXT",
		"CASTLE0.PIC",
		"CASTLE1.PIC",
		"CASTLE2.PIC",
		"CASTLE3.PIC",
		"CASTLE4.PIC",
		"CBACK.PIC",
		"CBACKS1.PIC",
		"CBACKS2.PIC",
		"CBACKS3.PIC",
		"CBRUSH0.PIC",
		"CBRUSH1.PIC",
		"CBRUSH2.PIC",
		"CBRUSH3.PIC",
		"CBRUSH4.PIC",
		"CBRUSH5.PIC",
		"CITYPIX1.PIC",
		"CITYPIX2.PIC",
		"CITYPIX3.PIC",
		//"CIV.EXE",
		//"CREDITS.TXT",
		"CUSTOM.PIC",
		"DIFFS.PIC",
		//"DISCOVR1.PAL",
		"DISCOVR1.PIC",
		//"DISCOVR2.PAL",
		"DISCOVR2.PIC",
		"DOCKER.PIC",
		//"EGRAPHIC.EXE",
		//"ERROR.TXT",
		//"FONTS.CV",
		"GOVT0A.PIC",
		"GOVT0M.PIC",
		"GOVT1A.PIC",
		"GOVT1M.PIC",
		"GOVT2A.PIC",
		"GOVT2M.PIC",
		"GOVT3A.PIC",
		//"HELP.TXT",
		//"HILL.PAL",
		"HILL.PIC",
		//"ICONPG1.PAL",
		"ICONPG1.PIC",
		"ICONPG2.PIC",
		"ICONPG3.PIC",
		"ICONPG4.PIC",
		"ICONPG5.PIC",
		"ICONPG6.PIC",
		"ICONPG7.PIC",
		"ICONPG8.PIC",
		//"ICONPGA.PAL",
		"ICONPGA.PIC",
		"ICONPGB.PIC",
		"ICONPGC.PIC",
		"ICONPGD.PIC",
		"ICONPGE.PIC",
		"ICONPGT1.PIC",
		"ICONPGT2.PIC",
		//"INTRO.TXT",
		//"INTRO3.TXT",
		"INVADER2.PIC",
		"INVADER3.PIC",
		"INVADERS.PIC",
		//"ISOUND.CVL",
		//"KING.TXT",
		//"KING00.PAL",
		"KING00.PIC",
		//"KING01.PAL",
		"KING01.PIC",
		//"KING02.PAL",
		"KING02.PIC",
		//"KING03.PAL",
		"KING03.PIC",
		//"KING04.PAL",
		"KING04.PIC",
		//"KING05.PAL",
		"KING05.PIC",
		//"KING06.PAL",
		"KING06.PIC",
		//"KING07.PAL",
		"KING07.PIC",
		//"KING08.PAL",
		"KING08.PIC",
		//"KING09.PAL",
		"KING09.PIC",
		//"KING10.PAL",
		"KING10.PIC",
		//"KING11.PAL",
		"KING11.PIC",
		//"KING12.PAL",
		"KING12.PIC",
		//"KING13.PAL",
		"KING13.PIC",
		"KINK00.PIC",
		"KINK03.PIC",
		"LOGO.PIC",
		"LOVE1.PIC",
		"LOVE2.PIC",
		"MAP.PIC",
		//"MGRAPHIC.EXE",
		//"MISC.EXE",
		//"NSOUND.CVL",
		"NUKE1.PIC",
		"PLANET1.PIC",
		"PLANET2.PIC",
		"POP.PIC",
		//"PRODUCE.TXT",
		//"READ.ME",
		"RIOT.PIC",
		"RIOT2.PIC",
		//"RSOUND.CVL",
		"SAD.PIC",
		"SETTLERS.PIC",
		"SLAG2.PIC",
		//"SLAM1.PAL",
		"SLAM1.PIC",
		"SLAM2.PIC",
		//"SP256.PAL",
		//"SP257.PAL",
		"SP257.PIC",
		"SP299.PIC",
		"SPACEST.PIC",
		"SPRITES.PIC",
		//"STORY.TXT",
		"TER257.PIC",
		//"TGRAPHIC.EXE",
		//"TORCH.PIC",
		//"TSOUND.CVL",
		"WONDERS.PIC",
		"WONDERS2.PIC"
/*
"LOGO.PIC",
"SP257.PIC",
"SP299.PIC",
"LOVE1.PIC",
"LOVE2.PIC",
//"MAP.PIC",
"ARCH.PIC",
"TER257.PIC",
"WONDERS.PIC",
"WONDERS2.PIC",
"BACK0A.PIC",
"BACK0M.PIC",
"BACK1A.PIC",
"BACK1M.PIC",
"BACK2A.PIC",
"BACK2M.PIC",
"BACK3A.PIC",
"BIRTH0.PIC",
"BIRTH1.PIC",
"BIRTH2.PIC",
"BIRTH3.PIC",
"BIRTH4.PIC",
"BIRTH5.PIC",
"BIRTH6.PIC",
"BIRTH7.PIC",
"BIRTH8.PIC",
"CASTLE0.PIC",
"CASTLE1.PIC",
"CASTLE2.PIC",
"CASTLE3.PIC",
"CASTLE4.PIC",
"CBACK.PIC",
"CBACKS.PIC",
"CBACKS1.PIC",
"CBACKS2.PIC",
"CBACKS3.PIC",
//"CBRUSH0.PIC",
//"CBRUSH1.PIC",
//"CBRUSH2.PIC",
//"CBRUSH3.PIC",
//"CBRUSH4.PIC",
//"CBRUSH5.PIC",
"CITYPIX1.PIC",
"CITYPIX2.PIC",
"CITYPIX3.PIC",
"CUSTOM.PIC",
"DIFFS.PIC",
"DISCOVR1.PIC",
"DISCOVR2.PIC",
"DOCKER.PIC",
"GOVT0A.PIC",
"GOVT0M.PIC",
"GOVT1A.PIC",
"GOVT1M.PIC",
"GOVT2A.PIC",
"GOVT2M.PIC",
"GOVT3A.PIC",
"HILL.PIC",
"ICONPG1.PIC",
"ICONPG2.PIC",
"ICONPG3.PIC",
"ICONPG4.PIC",
"ICONPG5.PIC",
"ICONPG6.PIC",
"ICONPG7.PIC",
"ICONPG8.PIC",
"ICONPGA.PIC",
"ICONPGB.PIC",
"ICONPGC.PIC",
"ICONPGD.PIC",
"ICONPGE.PIC",
"ICONPGT1.PIC",
"ICONPGT2.PIC",
"INVADER2.PIC",
"INVADER3.PIC",
"INVADERS.PIC",
"KING00.PIC",
"KING01.PIC",
"KING02.PIC",
"KING03.PIC",
"KING04.PIC",
"KING05.PIC",
"KING06.PIC",
"KING07.PIC",
"KING08.PIC",
"KING09.PIC",
"KING10.PIC",
"KING11.PIC",
"KING12.PIC",
"KING13.PIC",
//"KINK00.PIC",
//"KINK03.PIC",
"NUKE1.PIC",
//"PLANET1.PIC",
"PLANET2.PIC",
"POP.PIC",
"RIOT.PIC",
"RIOT2.PIC",
"SAD.PIC",
"SETTLERS.PIC",
//"SLAG2.PIC",
//"SLAM1.PIC",
//"SLAM2.PIC",
//"SPACEST.PIC",
//"SPRITES.PIC",
*/
};

template <typename T, int Size>
T* begin(T (&array)[Size]) {
    return array;
}
template <typename T, int Size>
T* end(T (&array)[Size]) {
    return array + Size;
}

std::vector<std::string> CivPicFiles(begin(CivPicFilesNames), end(CivPicFilesNames));

#endif /* !APP_HPP */
